apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tenant.configurationSecret }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: minio
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER={{ .Values.credentials.rootUser | quote }}
    export MINIO_ROOT_PASSWORD={{ .Values.credentials.rootPassword | quote }}
    export MINIO_BROWSER=on
