# Имя ресурсов в кластере (StatefulSet, Pod, Service и т.д.)
fullnameOverride: vault
global:
  enabled: true
  serverTelemetry:
    prometheusOperator: true
  tlsDisable: false
injector:
  image:
    repository: "hashicorp/vault-k8s"
    tag: "1.2.1"
  agentImage:
    repository: "hashicorp/vault"
    tag: 1.14.0
  certs:
    secretName: vault-injector-tls
    caBundle: ""
  webhook:
    annotations:
      cert-manager.io/inject-ca-from: vault/vault-injector-tls
  enabled: true
  resources:
    limits:
      cpu: 260m
      memory: 256Mi
    requests:
      cpu: 260m
      memory: 256Mi
server:
  auditStorage:
    enabled: true
    mountPath: /vault/audit
    size: 1Gi
    storageClass: topolvm-provisioner
  dataStorage:
    enabled: true
    mountPath: /vault/data
    size: 1Gi
    storageClass: topolvm-provisioner
  enabled: true
  extraEnvironmentVars:
    VAULT_CACERT: /vault/userconfig/vault-tls/ca.crt
  extraVolumes:
    - name: vault-tls
      type: secret
  ha:
    apiAddr: "https://$(VAULT_K8S_POD_NAME).vault-internal:8200"
    enabled: true
    raft:
      config: >
        ui = true
        disable_mlock = true
        listener "tcp" {
          tls_disable = false
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/vault/userconfig/vault-tls/tls.crt"
          tls_key_file = "/vault/userconfig/vault-tls/tls.key"
          tls_client_ca_file = "/vault/userconfig/vault-tls/ca.crt"
          telemetry {
            unauthenticated_metrics_access = "true"
          }
        }
        telemetry {
          prometheus_retention_time = "30s"
          disable_hostname = true
        }
        storage "raft" {
          path = "/vault/data"
          retry_join {
            leader_api_addr = "https://vault-0.vault-internal:8200"
            leader_ca_cert_file = "/vault/userconfig/vault-tls/ca.crt"
            leader_client_cert_file = "/vault/userconfig/vault-tls/tls.crt"
            leader_client_key_file = "/vault/userconfig/vault-tls/tls.key"
          }
        }
        service_registration "kubernetes" {}
      enabled: true
      setNodeId: true
    replicas: 1
  image:
    repository: "hashicorp/vault"
    tag: 1.14.0
  ingress:
    activeService: true
    annotations:
      cert-manager.io/cluster-issuer: "lab-home-ca-issuer"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: vault.lab-home.com
        paths: []
    tls:
      - secretName: vault-ingress-tls
        hosts:
          - vault.lab-home.com
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
    port: 8200
    timeoutSeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  readinessProbe:
    enabled: true
    path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
    port: 8200
    timeoutSeconds: 10
    periodSeconds: 5
    initialDelaySeconds: 10
    failureThreshold: 5
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  updateStrategyType: OnDelete
serverTelemetry:
  prometheusRules:
    enabled: true
    rules: []
  serviceMonitor:
    enabled: true
ui:
  enabled: true
  externalPort: 8200
  serviceNodePort: null
  serviceType: ClusterIP

csi:
  image:
    repository: "hashicorp/vault-csi-provider"
    tag: "1.4.0"
