certmanager:
  install: false
upgradeCheck:
  enabled: false
nginx-ingress:
  enabled: false
prometheus:
  install: false
registry:
  enabled: false
gitlab-runner:
  install: false

global:
  gitlabVersion: "16.4.1"
  edition: ce
  hosts:
    domain: lab-home.com
    gitlab:
      hostnameOverride: gitlab-test.lab-home.com
    https: true
  ingress:
    configureCertmanager: false
    class: nginx
    annotations:
      cert-manager.io/cluster-issuer: "lab-home-ca-issuer"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls:
      enabled: true
  kas:
    enabled: false
  appConfig:
    object_store:
      enabled: true
      proxy_download: true
      connection:
        secret: gitlab-s3-cfg
        key: connection
      createBucketsJob:
        enabled: false
    lfs:
      enabled: true
      proxy_download: true
      bucket: gitlab-test-lab-home-lfs
      connection: {}
    artifacts:
      enabled: true
      proxy_download: true
      bucket: gitlab-test-lab-home-artifacts
      connection: {}
    uploads:
      enabled: true
      proxy_download: true
      bucket: gitlab-test-lab-home-uploads
      connection: {}
    packages:
      enabled: true
      proxy_download: true
      bucket: gitlab-test-lab-home-packages
      connection: {}
    externalDiffs:
      enabled: true
      when: outdated
      proxy_download: true
      bucket: gitlab-test-lab-home-mr-diffs
      connection: {}
    terraformState:
      enabled: true
      bucket: gitlab-test-lab-home-terraform-state
      connection: {}
    ciSecureFiles:
      enabled: true
      bucket: gitlab-test-lab-home-ci-secure-files
      connection:
        secret: gitlab-s3-cfg
        key: connection
    dependencyProxy:
      enabled: true
      proxy_download: true
      bucket: gitlab-test-lab-home-dependency-proxy
      connection: {}
    backups:
      bucket: gitlab-test-lab-home-backups
      tmpBucket: gitlab-test-lab-home-backup-tmp
  minio:
    enabled: false
  grafana:
    enabled: false

gitlab:
  upgradeCheck:
    enabled: false
  webservice:
    replicas: 1
    minReplicas: 1
    maxReplicas: 1
    deployment:
      livenessProbe:
        initialDelaySeconds: 200
      readinessProbe:
        initialDelaySeconds: 120
        failureThreshold: 12
    resources:
      requests:
        cpu: 300m
        memory: 2G
      limits:
        cpu: "1"
        memory: 4G
  sidekiq:
    replicas: 1
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: 400m
        memory: 1G
      limits:
        cpu: "1"
        memory: 2G
  gitaly:
    image:
      tag: v16.4.1
    replicas: 1
    persistence:
      storageClass: topolvm-provisioner
      size: 5Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  gitlab-shell:
    replicas: 1
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
  kas:
    enabled: false
  gitlab-exporter:
    enabled: false
  toolbox:
    enabled: true
    image:
      repository: harbor.lab-home.com/gitlab/gitlab-toolbox-ce
      tag: v16.4.1-pg16
    backups:
      cron:
        enabled: true
        schedule: "0 2 * * *"   # как prod (lab-home.yaml)
        extraArgs: --skip artifacts
        successfulJobsHistoryLimit: 5
        failedJobsHistoryLimit: 3
        backoffLimit: 2
        restartPolicy: Never
        persistence:
          enabled: true
          size: 2Gi
          storageClass: topolvm-provisioner
          useGenericEphemeralVolume: false
      objectStorage:
        backend: s3
        config:
          secret: gitlab-s3-cfg
          key: s3cmd

postgresql:
  image:
    repository: bitnamilegacy/postgresql
    tag: "16.6.0"
  metrics:
    enabled: true
    image:
      repository: bitnamilegacy/postgres-exporter
      tag: 0.15.0-debian-11-r7
  auth:
    username: gitlab
    password: "gitlab123"
  primary:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: topolvm-provisioner
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

redis:
  install: true
  image:
    repository: bitnamilegacy/redis
    tag: 7.2.4-debian-12-r9
  metrics:
    enabled: true
    image:
      repository: bitnamilegacy/redis-exporter
      tag: 1.58.0-debian-12-r4
  architecture: standalone
  master:
    persistence:
      enabled: true
      size: 2Gi
      storageClass: topolvm-provisioner
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi
  replica:
    replicaCount: 0
