apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: prometheus-stack
  labels:
    app.kubernetes.io/part-of: prometheus-stack
    app.kubernetes.io/component: grafana
type: Opaque
stringData:
  admin-user: admin
  admin-password: "<ADMIN_PASSWORD>"
