# Harbor values для окружения lab-home (чарт helm/charts/harbor-1.18.0)
externalURL: https://harbor.lab-home.com
harborAdminPassword: "ChangeMeAfterInstall"

expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: harbor-tls
  ingress:
    hosts:
      core: harbor.lab-home.com
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: "selfsigned-issuer"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

# Лимиты ресурсов для компонентов Harbor
core:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

portal:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

nginx:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

jobservice:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

registry:
  registry:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  controller:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

trivy:
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

database:
  internal:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

redis:
  internal:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

# TopolVM — тома бэкапятся Velero (не hostPath). Имя класса: topolvm-provisioner (или sc-topolvm при custom values).
persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      existingClaim: harbor-registry-migr
      storageClass: "topolvm-provisioner"
      size: 5Gi
    jobservice:
      jobLog:
        existingClaim: harbor-jobservice-migr
        storageClass: "topolvm-provisioner"
        size: 1Gi
    database:
      existingClaim: database-data-harbor-database-0-migr
      storageClass: "topolvm-provisioner"
      size: 1Gi
    redis:
      existingClaim: data-harbor-redis-0-migr
      storageClass: "topolvm-provisioner"
      size: 1Gi
    trivy:
      existingClaim: data-harbor-trivy-0-migr
      storageClass: "topolvm-provisioner"
      size: 5Gi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
