# Default values for minio-tenant
# Переопределения — в helm/custom-values/lab-home-tenant.yaml

tenant:
  name: minio-tenant
  image: minio/minio:RELEASE.2023-09-04T19-57-37Z
  configurationSecret: storage-configuration
  pools:
    - name: pool-0
      servers: 1
      volumesPerServer: 1
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 2000m
          memory: 2Gi
      volumeClaimTemplate:
        storageClassName: local-path
        size: 10Gi

credentials:
  rootUser: minioadmin
  rootPassword: minioadmin123

ingress:
  enabled: true
  host: minio.lab-home.com
  ingressClassName: nginx
  annotations: {}
  tlsSecret: minio-tenant-console-tls
