{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ include "gitlab-tokens-exporter.namespace" . }}
  labels:
    {{- include "gitlab-tokens-exporter.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: {{ .Values.secret.key }}
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.key }}
        property: {{ .Values.externalSecrets.remoteRef.property }}
{{- end }}
