{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
  namespace: {{ include "gitlab-tokens-exporter.namespace" . }}
  labels:
    {{- include "gitlab-tokens-exporter.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.externalSecrets.vault.server | quote }}
      path: {{ .Values.externalSecrets.vault.path | quote }}
      version: {{ .Values.externalSecrets.vault.version | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.externalSecrets.vault.kubernetes.mountPath | quote }}
          role: {{ .Values.externalSecrets.vault.kubernetes.role | quote }}
          serviceAccountRef:
            name: {{ include "gitlab-tokens-exporter.serviceAccountName" . }}
{{- end }}
