---
# ArgoCD Application для Prometheus Stack (kube-prometheus-stack)
# Структура как в harbor и vault: локальный path, values в custom-values
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/mistermedved01/lab-home.git
    path: 03-argocd/prometheus-stack/helm/charts/kube-prometheus-stack-81.6.0
    targetRevision: main
    helm:
      releaseName: prometheus-stack
      valueFiles:
        - ../../custom-values/lab-home.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - SkipCRDs=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
