---
# ArgoCD Application для Nexus Repository Manager
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/mistermedved01/lab-home.git
    path: 03-argocd/nexus/helm/charts/nexus-repository-manager-64.2.0
    targetRevision: main
    helm:
      releaseName: nexus
      valueFiles:
        - ../../custom-values/lab-home.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: nexus

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
