---
# ArgoCD Application для Vault
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://github.com/mistermedved01/lab-home.git
      path: 03-argocd/vault/manifests
      targetRevision: main
    - repoURL: https://github.com/mistermedved01/lab-home.git
      path: 03-argocd/vault/helm/charts/vault-1.14.0
      targetRevision: main
      helm:
        releaseName: vault
        valueFiles:
          - $values/03-argocd/vault/helm/custom-values/lab-home.yaml
    - repoURL: https://github.com/mistermedved01/lab-home.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: vault-agent-injector-cfg
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
