---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-tokens-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/mistermedved01/lab-home.git
    path: 03-argocd/gitlab-tokens-exporter/helm/charts/gitlab-tokens-exporter-0.1.0
    targetRevision: main
    helm:
      releaseName: gitlab-tokens-exporter
      valueFiles:
        - ../../custom-values/lab-home.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
